// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuGnfKp2W_H-mUkRJS02NaLLISk2xuTIw',
    appId: '1:394085632588:web:9dfe3e04bc2826b33082e9',
    messagingSenderId: '394085632588',
    projectId: 'first-app-f4708',
    authDomain: 'first-app-f4708.firebaseapp.com',
    databaseURL: 'https://first-app-f4708-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-f4708.firebasestorage.app',
    measurementId: 'G-Y0V5FFCR7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA71WJ0GznyEL4E1mva2yarQauR7-BduU',
    appId: '1:394085632588:android:0eed58de63f1c81d3082e9',
    messagingSenderId: '394085632588',
    projectId: 'first-app-f4708',
    databaseURL: 'https://first-app-f4708-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-f4708.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvrPyRC9RGMLi9JmIPTxWb-IwOB6-5LCw',
    appId: '1:394085632588:ios:0ffb2bd2d43b33523082e9',
    messagingSenderId: '394085632588',
    projectId: 'first-app-f4708',
    databaseURL: 'https://first-app-f4708-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-f4708.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvrPyRC9RGMLi9JmIPTxWb-IwOB6-5LCw',
    appId: '1:394085632588:ios:0ffb2bd2d43b33523082e9',
    messagingSenderId: '394085632588',
    projectId: 'first-app-f4708',
    databaseURL: 'https://first-app-f4708-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-f4708.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuGnfKp2W_H-mUkRJS02NaLLISk2xuTIw',
    appId: '1:394085632588:web:75ea6563094e89fa3082e9',
    messagingSenderId: '394085632588',
    projectId: 'first-app-f4708',
    authDomain: 'first-app-f4708.firebaseapp.com',
    databaseURL: 'https://first-app-f4708-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-f4708.firebasestorage.app',
    measurementId: 'G-HC0DPTPZ7W',
  );

}