// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhkWdopTDjKb8iqxtfivFzzo0S7CHICsU',
    appId: '1:716800246460:web:4ab93669285ef9a79586b9',
    messagingSenderId: '716800246460',
    projectId: 'fasum-f6529',
    authDomain: 'fasum-f6529.firebaseapp.com',
    storageBucket: 'fasum-f6529.firebasestorage.app',
    measurementId: 'G-32F8ETCD9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_GJHF_qieWXcN2t9whbXa_I3oStoFcPs',
    appId: '1:716800246460:android:47d178096711b52e9586b9',
    messagingSenderId: '716800246460',
    projectId: 'fasum-f6529',
    storageBucket: 'fasum-f6529.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_R7a-bMHPhQc2kBrbDDFHjDr2pTwru0A',
    appId: '1:716800246460:ios:322c4559c357ea809586b9',
    messagingSenderId: '716800246460',
    projectId: 'fasum-f6529',
    storageBucket: 'fasum-f6529.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_R7a-bMHPhQc2kBrbDDFHjDr2pTwru0A',
    appId: '1:716800246460:ios:322c4559c357ea809586b9',
    messagingSenderId: '716800246460',
    projectId: 'fasum-f6529',
    storageBucket: 'fasum-f6529.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhkWdopTDjKb8iqxtfivFzzo0S7CHICsU',
    appId: '1:716800246460:web:b0ea01e5ee9a9a4a9586b9',
    messagingSenderId: '716800246460',
    projectId: 'fasum-f6529',
    authDomain: 'fasum-f6529.firebaseapp.com',
    storageBucket: 'fasum-f6529.firebasestorage.app',
    measurementId: 'G-BYY4DG501T',
  );
}
