// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzUe0cQV07HRIHYbBJaVTmQQrnY84QqLA',
    appId: '1:380162568202:web:e4a2dcd08295136299aff3',
    messagingSenderId: '380162568202',
    projectId: 'latihanuts-ec3c2',
    authDomain: 'latihanuts-ec3c2.firebaseapp.com',
    storageBucket: 'latihanuts-ec3c2.firebasestorage.app',
    measurementId: 'G-0DMX2L4GNP',
    databaseURL: 'https://latihanuts-ec3c2-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABIpoI-kR0PA_iFbmnhmaPMS51qK9osc4',
    appId: '1:380162568202:android:019d4802f5a15cc799aff3',
    messagingSenderId: '380162568202',
    projectId: 'latihanuts-ec3c2',
    storageBucket: 'latihanuts-ec3c2.firebasestorage.app',
    databaseURL: 'https://latihanuts-ec3c2-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl4mxy6gqpRdhLteSt9iVYc_j2ZEGP4fY',
    appId: '1:380162568202:ios:45c9eae3b05db6e699aff3',
    messagingSenderId: '380162568202',
    projectId: 'latihanuts-ec3c2',
    storageBucket: 'latihanuts-ec3c2.firebasestorage.app',
    iosBundleId: 'com.example.latihanuts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl4mxy6gqpRdhLteSt9iVYc_j2ZEGP4fY',
    appId: '1:380162568202:ios:45c9eae3b05db6e699aff3',
    messagingSenderId: '380162568202',
    projectId: 'latihanuts-ec3c2',
    storageBucket: 'latihanuts-ec3c2.firebasestorage.app',
    iosBundleId: 'com.example.latihanuts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzUe0cQV07HRIHYbBJaVTmQQrnY84QqLA',
    appId: '1:380162568202:web:018e820538ab5b9999aff3',
    messagingSenderId: '380162568202',
    projectId: 'latihanuts-ec3c2',
    authDomain: 'latihanuts-ec3c2.firebaseapp.com',
    storageBucket: 'latihanuts-ec3c2.firebasestorage.app',
    measurementId: 'G-8R4LS6P7V7',
  );
}
